import Nav from '../components/Nav'

export const metadata = {
  title: 'Disclaimers - Vector | WA',
  description: 'Data sources, methodology, limitations, and contact for Vector | WA.',
}

function H2({ children }) {
  return (
    <h2 style={{
      fontSize: 11,
      letterSpacing: '0.14em',
      textTransform: 'uppercase',
      fontWeight: 600,
      color: '#b8975a',
      marginTop: 32,
      marginBottom: 10,
    }}>
      {children}
    </h2>
  )
}

function P({ children }) {
  return (
    <p style={{
      fontSize: 14,
      lineHeight: 1.7,
      color: '#d8dce3',
      marginBottom: 12,
    }}>
      {children}
    </p>
  )
}

export default function DisclaimersPage() {
  return (
    <>
      <Nav />
      <main style={{
        maxWidth: 760,
        margin: '0 auto',
        padding: '32px 24px 80px',
        fontFamily: 'var(--font-karla, Karla, sans-serif)',
      }}>
        <div style={{
          fontSize: 10,
          letterSpacing: '0.16em',
          textTransform: 'uppercase',
          color: '#7a8090',
          marginBottom: 8,
        }}>
          Vector | WA
        </div>
        <h1 style={{
          fontSize: 26,
          fontWeight: 700,
          color: '#f1f3f7',
          marginBottom: 14,
          letterSpacing: '-0.01em',
        }}>
          Disclaimers
        </h1>

        <P>
          Vector | WA is a Washington State legislative intelligence tool. This page explains what Vector | WA is, where the data comes from, how the signals are generated, and what Vector | WA is not.
        </P>

        <H2>Data sources and freshness</H2>
        <P>
          Vector | WA pulls from the Washington State Legislature's public records: bill text, committee actions, roll calls, fiscal notes, and floor calendars. The data is mirrored nightly into Vector | WA's database. Between syncs, the site reflects the state of the record at the last refresh, not the live docket. A timestamp on each bill page shows the last sync.
        </P>

        <H2>How signals are generated</H2>
        <P>
          Every bill receives a trajectory score from 0 to 99. The score is a weighted composite of five signals (committee placement, vote margins, fiscal note status, calendar movement, and companion status), adjusted by documented X factors when a bill sits outside the ordinary procedural path. Scores are bucketed into four tiers: HIGH (75 to 99), MODERATE (60 to 74), LOW (45 to 59), and VERY LOW (0 to 44). Bucket thresholds are calibrated across three biennia of Washington State session data (2021-22, 2023-24, 2025-26 &mdash; 8,062 bills) and rechecked each session. See the methodology page for the full calibration table.
        </P>

        <H2>Algorithmic authorship</H2>
        <P>
          Scores, tiers, and momentum indicators in Vector | WA are produced by algorithm, not by a human analyst. No human writes or reviews individual bill scores before they appear on the site. Bill summaries on each bill page are generated by a large language model from the bill's official text and metadata, also without individual human review. The underlying bill text and procedural record come directly from the Washington State Legislature.
        </P>

        <H2>Model uncertainty</H2>
        <P>
          A trajectory score is a signal about where a bill is likely heading based on its procedural record. It is not a prediction, a guarantee, or a probability in the strict statistical sense. Bills with identical scores can and do reach different outcomes. Vector | WA makes no representation that any score will correspond to any particular legislative result.
        </P>

        <H2>Interim-period framing</H2>
        <P>
          Between legislative sessions, trajectory scores reflect a bill's terminal position in the most recent session, not its prospects in the next one. Carry-over and prefile activity are labeled separately. Users should treat interim scores as historical, not predictive.
        </P>

        <H2>Not legal advice</H2>
        <P>
          Vector | WA is an intelligence tool. It is not legal advice and not a substitute for counsel. Vector | WA is nonpartisan &mdash; it doesn&rsquo;t endorse candidates, take partisan positions, or recommend how anyone should act on legislative information. Its job is to make the record easier to read.
        </P>

        <H2>Who Vector | WA is for</H2>
        <P>
          Vector | WA is built for anyone who works with Washington State legislation &mdash; legislative staff, advocates, registered lobbyists, journalists, researchers, students, and the general public. Vector | WA is not a registered lobbying entity and does not represent clients before the Legislature or state agencies.
        </P>

        <H2>Corrections and contact</H2>
        <P>
          The Washington State Legislature's public record is the authoritative source for any bill referenced in Vector | WA. Where Vector | WA and the Legislature's record disagree, the Legislature's record controls. Corrections and questions: colin@shorepine.org.
        </P>
      </main>
    </>
  )
}