"use client"

import Link from 'next/link'
import { useViewer } from '../../lib/viewer-capabilities'

/**
 * Global app footer -- mounted in the root layout and rendered on every
 * route. Because the same component lands across all three layers (public,
 * owner, client portal), the bottom attribution line BRANCHES on viewer
 * role to keep the public-vs-internal brand split intact (Phase 2 directive
 * D1 + Universal Guardrail G6 -- Layer Discipline).
 *
 *   role === 'public'  -> forward-looking launch framing (Vector | WA stands
 *                         alone publicly until Shorepine GR launches Sep 2027).
 *   role === 'owner'   -> firm attribution restored -- operator IS Shorepine
 *                         on /watchlist, /settings, /admin/*, /auth/callback.
 *   role === 'client'  -> bottom strip suppressed; the client portal pages
 *                         render their own inline Shorepine attribution.
 *
 * The first two lines (legal-disclosure + disclaimers/about links) render on
 * every layer regardless. Those are universal, layer-agnostic content.
 *
 * Thread 24 (2026-04-26) -- added the About link inline alongside Full
 * disclaimers. The About page is public-shaped and exists for all viewers,
 * so the link is universal copy; only the bottom attribution stays branched.
 */
export default function Footer() {
  const { capabilities, loading } = useViewer()
  const role = capabilities?.role

  let bottomLine = null
  if (!loading) {
    if (role === 'public') {
      bottomLine = 'Public site launching mid 2027.'
    } else if (role === 'owner') {
      bottomLine = 'Vector | WA -- a product of Shorepine Government Relations.'
    }
  }

  return (
    <footer
      style={{
        borderTop: '1px solid #232530',
        background: '#0e1014',
        padding: '16px 24px 90px 24px',
        fontFamily: 'var(--font-karla, Karla, sans-serif)',
        fontSize: 12,
        lineHeight: 1.55,
        color: '#7a8090',
        textAlign: 'center',
      }}
    >
      <div style={{ maxWidth: 860, margin: '0 auto' }}>
        <div style={{ marginBottom: 6 }}>
          Vector | WA &mdash; Washington State legislative intelligence. Signals are generated by algorithm from public Washington State Legislature records and refreshed nightly.
        </div>
        <div style={{ marginBottom: 10 }}>
          Not legal advice. Nonpartisan. Free.{' '}
          <Link href="/disclaimers" style={{ color: '#d4b47a', textDecoration: 'underline' }}>
            Full disclaimers
          </Link>
          {' \u00b7 '}
          <Link href="/about" style={{ color: '#d4b47a', textDecoration: 'underline' }}>
            About Vector
          </Link>
          .
        </div>
        {bottomLine && (
          <div style={{
            paddingTop: 10,
            borderTop: '1px solid #1e2028',
            color: '#5a6070',
            fontSize: 11,
            letterSpacing: '0.02em',
          }}>
            {bottomLine}
          </div>
        )}
      </div>
    </footer>
  )
}