'use client'

import Link from 'next/link'

export default function Footer() {
  return (
    <footer
      style={{
        borderTop: '1px solid #232530',
        background: '#0e1014',
        padding: '20px 24px',
        marginTop: 48,
        fontFamily: 'var(--font-karla, Karla, sans-serif)',
        fontSize: 12,
        lineHeight: 1.55,
        color: '#7a8090',
        textAlign: 'center',
      }}
    >
      <div style={{ maxWidth: 860, margin: '0 auto' }}>
        <div style={{ marginBottom: 6 }}>
          Vector | WA is a product of{' '}
          <span style={{ color: '#b8975a' }}>Shorepine Government Relations</span>
          . Signals are generated by algorithm from public Washington State Legislature records and refreshed nightly.
        </div>
        <div>
          Not legal advice, not a lobbying solicitation.{' '}
          <Link href="/disclaimers" style={{ color: '#d4b47a', textDecoration: 'underline' }}>
            Full disclaimers
          </Link>
          .
        </div>
      </div>
    </footer>
  )
}